[sh/meta-source/wrapper] Add gin login check

diff --git a/staging/sh/meta_source/meta_source_from_datacite b/staging/sh/meta_source/meta_source_from_datacite
--- a/staging/sh/meta_source/meta_source_from_datacite
+++ b/staging/sh/meta_source/meta_source_from_datacite
@@ -9,6 +9,12 @@
 # script requires an installed gin client with a logged in user able to
 # to download the gin:G-Node/DOIMetadata and gin:G-Node/meta-source repositories.
 
+echo "... checking doi fork"
+if ! gin repoinfo G-Node/DOIMetadata | grep -iq "[error]"; then
+  echo "... could not access G-Node/DOIMetadata; check gin login"
+  exit 1
+fi
+
 # paths and scripts
 ROOT=/home/$USER/Chaos/staging/meta_source
 CRCNS_SCRIPT_LOCACTION=/home/$USER/Chaos/work/snippets/staging/sh/meta_source/
